### ISSUE TITLE
Can not be installed on expo development client

### ISSUE THREAD

**Issue by moedeveloper** [nandorojo/zeego#65]
I Am getting the following when i try to install this library in expo development client
npx expo install expo-build-properites
› Installing 1 other package using npm
> npm install --save expo-build-properites
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/expo-build-properites - Not found
npm ERR! 404 
npm ERR! 404  'expo-build-properites@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /Users/mo3/.npm/_logs/2023-10-16T06_47_10_194Z-debug-0.log
Error: npm exited with non-zero code: 1
Error: npm exited with non-zero code: 1
    at ChildProcess.completionListener (/Users/mo3/Desktop/Almanbar-cli/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:632:26)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
    ...
    at spawnAsync (/Users/mo3/Desktop/Almanbar-cli/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at NpmPackageManager.runAsync (/Users/mo3/Desktop/Almanbar-cli/node_modules/@expo/package-manager/build/node/BasePackageManager.js:38:42)
    at /Users/mo3/Desktop/Almanbar-cli/node_modules/@expo/package-manager/build/node/NpmPackageManager.js:39:20
    at /Users/mo3/Desktop/Almanbar-cli/node_modules/@expo/package-manager/build/utils/spawn.js:19:34
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    
    
    I Am using expo SDK 49
    latest react native, the way i install it is npx expo install expo-build-properites

**Comment by nandorojo** [comment]
You misspelled it
